
- hosts: 10.0.5.5
  vars_prompt:
    - name: admin_password
      prompt: "Enter the local administrator password"
      private: yes

  tasks:
    - name: Set local administrator password
      win_user:
        name: Administrator
        password: "{{ admin_password }}"
        update_password: on_create

    - name: Set the hostname
      win_hostname:
        name: dc-blue1

    - name: Reboot after hostname change
      win_reboot:

    - name: Create a new forest and domain
      win_domain:
        dns_domain_name: BLUE.local
        safe_mode_password: "{{ admin_password }}"
      register: domain_install

    - name: Reboot after domain creation
      win_reboot:
        test_command: 'exit (Get-Service -Name DNS).Status -ne "Running"'
        shutdown_timeout: 600
        reboot_timeout: 600

    - name: Add DNS server forwarder
      win_shell: |
        Add-DnsServerForwarder -IPAddress "10.0.5.2"


    - name: Add user 'deployer' to Domain Admins
      win_shell: |
        Add-ADGroupMember -Identity "Domain Admins" -Members "deployer"


    - name: Create OU structure
      win_shell: |
        New-ADOrganizationalUnit -Name "blue1" -Path "DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name "Accounts" -Path "OU=blue1,DC=BLUE,DC=local" 
        New-ADOrganizationalUnit -Name "Groups" -Path "OU=blue1,DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name "Computers" -Path "OU=blue1,DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name "Servers" -Path "OU=Computers,OU=blue1,DC=BLUE,DC=local"
        New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Computers,OU=blue1,DC=BLUE,DC=local"